language: erlang

otp_release:
  - R16B03

cache: apt

branches:
  only:
    - master

install: true

before_install:
  - sudo hostname travis-vm.local
  - mvn clean package

script: make get-rebar all ct

after_failure:
  - cat src/test/common_test/logs/raw.log
